up:
	docker-compose -f docker/docker-compose.yml build lambda-service

exe:
	docker-compose -f docker/docker-compose.yml up lambda-service

run:
	docker-compose -f docker/docker-compose.yml run --rm lambda-service /bin/bash

