AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FastApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.9
      CodeUri: ./app
      MemorySize: 128
      Timeout: 10
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
